baseUrl: "http://localhost:1313/"
languageCode: en
title: cPanel Project
theme: PaperMod
staticDir: ["static"]
paginate: 5

# needed for search capability
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    - name: Breakfast
      url: categories/breakfast/
      weight: 1
    - name: Lunch
      url: categories/lunch/
      weight: 2
    - name: Dinner
      url: categories/dinner/
      weight: 3
    - name: Categories
      url: categories/
      weight: 4
    - name: Search
      url: search/
      weight: 5

params:
  env: production
  homeInfoParams:
      Title: "Title goes here..."
      Content: >
          Content goes here...